In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_excel ('drybean.xlsx')
df.head(20)

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0   28395.0    610.291       208.178117       173.888747      1.197191   
1   28734.0    638.018       200.524796       182.734419      1.097356   
2   29380.0    624.110       212.826130       175.931143      1.209713   
3   30008.0    645.884       210.557999       182.516516      1.153638   
4   30140.0    620.134       201.847882       190.279279      1.060798   
5   30279.0    634.927       212.560556       181.510182      1.171067   
6   30477.0    670.033       211.050155       184.039050      1.146768   
7   30519.0    629.727       212.996755       182.737204      1.165591   
8   30685.0    635.681       213.534145       183.157146      1.165852   
9   30834.0    631.934       217.227813       180.897469      1.200834   
10  30917.0    640.765       213.560089       184.439871      1.157885   
11  31091.0    638.558       210.486255       188.326848      1.117665   
12  31107.0    640.594       214.648549       184.969253      1.160455   
13  31158.0    642.626       216.484836       183.644312      1.178827   
14  31158.0    641.105       212.066975       187.192960      1.132879   
15  31178.0    636.888              NaN       186.562088      1.141582   
16  31202.0    644.454       215.640695       184.471684      1.168964   
17  31203.0    639.782       215.067737       184.874876      1.163315   
18  31272.0    638.666       212.450319       187.535939      1.132851   
19  31335.0    635.011       216.790092       184.163440      1.177161   

    Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0       0.549812       28715     190.141097  0.763923  0.988856   0.958027   
1       0.411785       29172     191.272750  0.783968  0.984986   0.887034   
2       0.562727       29690     193.410904  0.778113  0.989559   0.947849   
3       0.498616       30724     195.467062  0.782681  0.976696   0.903936   
4       0.333680       30417     195.896503  0.773098  0.990893        NaN   
5       0.520401       30600     196.347702  0.775688  0.989510   0.943852   
6       0.489478       30970     196.988633  0.762402  0.984081   0.853080   
7       0.513760       30847            NaN  0.770682  0.989367   0.967109   
8       0.514081       31044     197.659696  0.771561  0.988436   0.954240   
9       0.553642       31120     198.139012  0.783683  0.990810   0.970278   
10      0.504102       31280     198.405512  0.770805  0.988395   0.946258   
11      0.446622       31458     198.963038  0.786377  0.988334   0.958173   
12      0.507366       31423     199.014227  0.761046  0.989944   0.952582   
13      0.529514       31492     199.177302  0.798759  0.989394   0.948119   
14      0.469924       31474     199.177302  0.781313  0.989960   0.952623   
15      0.482352       31520     199.241217  0.764110  0.989150   0.965900   
16      0.517871       31573     199.317887  0.779193  0.988249   0.944079   
17      0.510947       31558     199.321081  0.762984  0.988751   0.957949   
18      0.469883       31593     199.541342  0.770322  0.989840   0.963425   
19      0.527587       31599     199.742237  0.774277  0.991645   0.976511   

    Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  Class  
0      0.913358      0.007332      0.003147      0.834222      0.998724  SEKER  
1      0.953861      0.006979      0.003564      0.909851      0.998430  SEKER  
2      0.908774      0.007244      0.003048      0.825871      0.999066  SEKER  
3      0.928329      0.007017      0.003215      0.861794      0.994199  SEKER  
4      0.970516      0.006697      0.003665      0.941900      0.999166  SEKER  
5      0.923726      0.007020      0.003153      0.853270      0.999236  SEKER  
6      0.933374      0.006925      0.003242      0.871186      0.999049  SEKER  
7      0.925480      0.006979      0.003158      0.856514      0.998345  SEKER  
8      0.925658      0.006959      0.003152      0.856844      0.998953  SEKER  
9  

In [3]:
df['MajorAxisLength'].fillna(df['MajorAxisLength'].mode()[0], inplace=True)
df['EquivDiameter'].fillna(df['EquivDiameter'].mode()[0], inplace=True)

In [4]:
df['roundness'].fillna(df['roundness'].mode()[0], inplace=True)
df['Area'].fillna(df['Area'].mode()[0], inplace=True)

In [5]:
df[df==np.inf]=np.nan
df.fillna(df.mean(), inplace=True)

In [6]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

In [7]:
df['Class']= label_encoder.fit_transform(df['Class'])
  
df['Class'].unique()

array([5, 0, 1, 2, 4, 6, 3])

In [8]:
feature_cols = ['Area', 'Perimeter', 'MajorAxisLength', 'MinorAxisLength',
       'AspectRation', 'Eccentricity', 'ConvexArea', 'EquivDiameter', 'Extent',
       'Solidity', 'roundness', 'Compactness', 'ShapeFactor1', 'ShapeFactor2',
       'ShapeFactor3', 'ShapeFactor4']

In [9]:
X = df[feature_cols] # Features
y = df['Class']

In [10]:
# split X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [13]:
## predict the model
y_pred = classifier.predict(X_test)

In [14]:
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
from sklearn import metrics

In [15]:

print(confusion_matrix(y_test, y_pred))
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))



[[283   0  21   0   3   3   9]
 [  0 111   0   0   0   0   0]
 [ 11   0 397   0   5   1   5]
 [  0   0   0 847   1  13  44]
 [  0   0   8   2 472   0   9]
 [  2   0   0   5   0 447  16]
 [  1   0   2  82  14   4 585]]
Accuracy: 0.9233029679694388


In [16]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.89      0.92       319
           1       1.00      1.00      1.00       111
           2       0.93      0.95      0.94       419
           3       0.90      0.94      0.92       905
           4       0.95      0.96      0.96       491
           5       0.96      0.95      0.95       470
           6       0.88      0.85      0.86       688

    accuracy                           0.92      3403
   macro avg       0.94      0.93      0.94      3403
weighted avg       0.92      0.92      0.92      3403

